replicaCount: 2

image:
  repository: reehanruhullah/dataphion_prac
  tag: v4

deployment:
  name: sample
  labels:
    app: sample
  containerName: python
  containerPort: 8000

service:
  name: py-service
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30007

serviceAccount:
  create: true
